### PR TITLE
Remove .vscode folder

### PR DESCRIPTION
**Pull request by jvanbaarsen**
We generally don't have editor related code in our codebase. I added it
to the .gitignore so people can have this locally if they choose to do
so.

### CODE REVIEW

**Comment by adamyeats** [comment]
@jvanbaarsen 👎 to this change, unfortunately. We need to keep this folder in the repo so that people opening the project are able to use the `stylelint` VScode integration.

**Comment by jvanbaarsen** [comment]
@xadamy Ok, but if someone tomorrow decided to use a different editor we have another folder in here. Aren't there different options for doing so?

**Comment by jvanbaarsen** [comment]
@xadamy I added it to gitignore, so you can locally have that file. Just not in the general repo.

**Comment by adamyeats** [comment]
@jvanbaarsen We're all using different editors anyway, aren't we? I would prefer if this were left in the repo, please. This saves anyone using VScode time trying to fix their syntax highlighting and linting.

**Comment by jvanbaarsen** [comment]
@xadamy Ok, let's wait for Tom's reply tomorrow as well. Maybe he has some good ideas on how to solve this.

**Comment by adamyeats** [comment]
@jvanbaarsen Actually, I'm going to change my mind on this one. While I'd rather keep this folder here to solve the issue for other vscode users, from what I understand your change keeps my local copy in place (?), so I'm less attached to this being here than I was before.

**Review by adamyeats — APPROVED** [review]

**Comment by adamyeats** [comment]
@tombruijn I'd still like to hear what you'd propose for making this config portable, if you have any ideas!

**Review by tombruijn — APPROVED** [review]

**Comment by tombruijn** [comment]
This seems like a personal editor setting. I have similar config like this for my vim configuration. 
Other than https://editorconfig.org/ type settings I would prefer to keep editor specific setting out of repositories. I wouldn't want to have to keep a per repo record of all the configs different editors need.

Gitignoring this directory and allowing users to have their local version seems good.
I would suggest adding files and directories like this to your global git config.

**Pull request merged**
